# environment
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
# grep
export GREP_OPTIONS='--color=auto'
# python
export PIP_DOWNLOAD_CACHE="$HOME/.pip/cache"
# postgres-app
export PATH="/Applications/Postgres.app/Contents/Versions/9.4/bin:$PATH"
export PATH="/Users/mgrouchy/Library/Python/2.7/bin/:$PATH"
# golang
export GOROOT=/usr/local/go/
export GOPATH=$HOME/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
